return {
  {
    "nvim-neo-tree/neo-tree.nvim",
    branch = "v3.x",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "MunifTanjim/nui.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    cmd = "Neotree",
    keys = {
      { "<C-n>", "<cmd>Neotree toggle left<cr>", desc = "Toggle Neo-tree" },
      { "<leader>nt", "<cmd>Neotree reveal_force_cwd left<cr>", desc = "Reveal file in Neo-tree" },
      { "<leader>nr", "<cmd>Neotree reveal_force_cwd left<cr>", desc = "Reset Neo-tree to current file" },
      { "<leader>nf", "<cmd>Neotree focus filesystem left<cr>", desc = "Focus Neo-tree files" },
      { "<leader>nb", "<cmd>Neotree buffers left<cr>", desc = "Neo-tree buffers" },
      { "<leader>ng", "<cmd>Neotree git_status left<cr>", desc = "Neo-tree git status" },
    },
    opts = {
      close_if_last_window = true,
      popup_border_style = "rounded",
      enable_git_status = true,
      enable_diagnostics = true,
      sort_case_insensitive = true,
      filesystem = {
        follow_current_file = {
          enabled = true,
          leave_dirs_open = true,
        },
        filtered_items = {
          visible = true,
          hide_dotfiles = false,
          hide_gitignored = false,
        },
        hijack_netrw_behavior = "open_current",
        use_libuv_file_watcher = true,
      },
      window = {
        position = "left",
        width = 32,
        mappings = {
          ["<space>"] = "none",
          ["<bs>"] = "none",
          ["n"] = "add",
          ["N"] = "none",
          ["l"] = "open",
          ["h"] = "close_node",
          ["o"] = "open",
          ["s"] = "open_split",
          ["v"] = "open_vsplit",
          ["t"] = "open_tabnew",
          ["a"] = "none",
          ["A"] = "add_directory",
          ["d"] = "delete",
          ["r"] = "rename",
          ["y"] = "copy_to_clipboard",
          ["x"] = "cut_to_clipboard",
          ["p"] = "paste_from_clipboard",
          ["R"] = "refresh",
          ["H"] = "toggle_hidden",
          ["/"] = "fuzzy_finder",
          ["P"] = { "toggle_preview", config = { use_float = true } },
        },
      },
    },
  },
}
